dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-09/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: C9fNj/WmIfplCoxXGctJ0lqxIy+I+bnhahaG6O8D2eBaHvWCYhyncoAye9dBkSdGkxdrSwxtUQBjQ91Wp+haJ9CM2DHYnEdlbGk120WNERsy+HADyXUFj3UKIZ1thIKca5Z9oOxCMFJEjrO8BSslp7TMnpppSQz/06HFqR7x9WDh4t0G9SoMg2k13AFD6XxngtUoGlN/JxVB7hK0HZ/EI991lOKlLXuuEZBD+ngM/ycnSA1be3ekZ2rgvcFkjzMv1/nKuZ7rp+R7SWfwZck4J6UdMH+qKvSl3PjCdy108h8erBUxURPoks1ZD9laDT0A+z+0WbxI9/lm3g57Kn8mR+EUPPqIvuibu02Q3oUa2v9QiOf7c5Awg0B7vj975ZMXlKDu+zcwlP4E3Ih1+nlpJiChB55+l12xJ9pFEQd6qBpWDt9uuO7EOVxBzMALX+U19cmF7SxLdNdHuCnmaemKhnaylg4cOy4sCxv68Zp42W1nxtoo5W597bcGYH9HZwXwFllbI/Lej9vn6SF3zTftSkLTCK51C+U5s5SEGSZLxYkkhzNDMe8Stko16WD7ykhthRlxy6JwE7U0qBR5nNfPJUdJAJ6WM7PNGd3aCkxcPiMjZKh50ZkI+k6Wt1fKpQqp/jKgd/g1VhR2p7LCAjhoTY/BHEhdHx9gspo5Y6zhrHE=
